name: Python CI

on:
  push:
    branches:
      - "**"
    tags:
      - "**"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: "Install poetry"
        run: |
          pip install poetry

      - name: "Install dependencies"
        run: |
          make install
          make build
          make publish
          make package-install

      - name: "Run linters"
        run: |
          make lint

      - name: "Run tests"
        run: |
          make tests
